In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM

In [49]:
df = yf.download('^GSPC', start = '2018-01-01', end='2021-01-15', progress = False)

In [50]:
df.head()

Open         High          Low        Close    Adj Close  \
Date                                                                          
2018-01-02  2683.729980  2695.889893  2682.360107  2695.810059  2695.810059   
2018-01-03  2697.850098  2714.370117  2697.770020  2713.060059  2713.060059   
2018-01-04  2719.310059  2729.290039  2719.070068  2723.989990  2723.989990   
2018-01-05  2731.330078  2743.449951  2727.919922  2743.149902  2743.149902   
2018-01-08  2742.669922  2748.510010  2737.600098  2747.709961  2747.709961   

                Volume  
Date                    
2018-01-02  3367250000  
2018-01-03  3538660000  
2018-01-04  3695260000  
2018-01-05  3236620000  
2018-01-08  3242650000

In [51]:
data = df.sort_index(ascending=True, axis=0)

In [52]:
data

Open         High          Low        Close    Adj Close  \
Date                                                                          
2018-01-02  2683.729980  2695.889893  2682.360107  2695.810059  2695.810059   
2018-01-03  2697.850098  2714.370117  2697.770020  2713.060059  2713.060059   
2018-01-04  2719.310059  2729.290039  2719.070068  2723.989990  2723.989990   
2018-01-05  2731.330078  2743.449951  2727.919922  2743.149902  2743.149902   
2018-01-08  2742.669922  2748.510010  2737.600098  2747.709961  2747.709961   
...                 ...          ...          ...          ...          ...   
2021-01-08  3815.050049  3826.689941  3783.600098  3824.679932  3824.679932   
2021-01-11  3803.139893  3817.860107  3789.020020  3799.610107  3799.610107   
2021-01-12  3801.620117  3810.780029  3776.510010  3801.189941  3801.189941   
2021-01-13  3802.229980  3820.959961  3791.500000  3809.840088  3809.840088   
2021-01-14  3814.979980  3823.600098  3792.860107  3795.540039  3795.540039   

                Volume  
Date                    
2018-01-02  3367250000  
2018-01-03  3538660000  
2018-01-04  3695260000  
2018-01-05  3236620000  
2018-01-08  3242650000  
...                ...  
2021-01-08  4764180000  
2021-01-11  4450500000  
2021-01-12  4977210000  
2021-01-13  4590420000  
2021-01-14  5180140000  

[765 rows x 6 columns]

In [53]:
dataset = data.values

In [54]:
dataset

array([[2.68372998e+03, 2.69588989e+03, 2.68236011e+03, 2.69581006e+03,
        2.69581006e+03, 3.36725000e+09],
       [2.69785010e+03, 2.71437012e+03, 2.69777002e+03, 2.71306006e+03,
        2.71306006e+03, 3.53866000e+09],
       [2.71931006e+03, 2.72929004e+03, 2.71907007e+03, 2.72398999e+03,
        2.72398999e+03, 3.69526000e+09],
       ...,
       [3.80162012e+03, 3.81078003e+03, 3.77651001e+03, 3.80118994e+03,
        3.80118994e+03, 4.97721000e+09],
       [3.80222998e+03, 3.82095996e+03, 3.79150000e+03, 3.80984009e+03,
        3.80984009e+03, 4.59042000e+09],
       [3.81497998e+03, 3.82360010e+03, 3.79286011e+03, 3.79554004e+03,
        3.79554004e+03, 5.18014000e+09]])

In [68]:
len_dataset = len(dataset)
train = dataset[0:round(len_dataset*0.9)]
valid = dataset[round(len_dataset*0.9):,:]

In [63]:
len(train_data)

688

In [64]:
len(valid_data)

77

In [65]:
len(train_data) + len(valid_data)

765

In [66]:
#converting dataset into x_train and y_train
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(dataset)

In [69]:
x_train, y_train = [], []
for i in range(60,len(train)):
    x_train.append(scaled_data[i-60:i,0])
    y_train.append(scaled_data[i,0])
x_train, y_train = np.array(x_train), np.array(y_train)

In [70]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [71]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1],1)))
model.add(LSTM(units=50))
model.add(Dense(1))

In [72]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, epochs=1, batch_size=1, verbose=2)

628/628 - 11s - loss: 0.0043


In [74]:
#predicting 246 values, using past 60 from the train data
inputs = data[len(data) - len(valid) - 60:].values
inputs = inputs.reshape(-1,1)
inputs  = scaler.transform(inputs)

ValueError: non-broadcastable output operand with shape (822,1) doesn't match the broadcast shape (822,6)

In [ ]:
# Tryiing other model

In [8]:
data_normaliser = preprocessing.MinMaxScaler()
data_normalised = data_normaliser.fit_transform(data)

In [9]:
data_normalised

array([[0.25782962, 0.25895824, 0.30637102, 0.28880232, 0.28880232,
        0.26725218],
       [0.26709272, 0.2710688 , 0.3159962 , 0.29966997, 0.29966997,
        0.28937488],
       [0.28117092, 0.2808462 , 0.32930041, 0.30655592, 0.30655592,
        0.30958616],
       ...,
       [0.99118967, 0.98957383, 0.98978757, 0.98520111, 0.98520111,
        0.47503856],
       [0.99158976, 0.996245  , 0.99915046, 0.99065077, 0.99065077,
        0.42511825],
       [0.99995403, 0.99797515, 1.        , 0.98164162, 0.98164162,
        0.50122933]])

In [10]:
history_points = 50
history_points

50

In [11]:
len(data_normalised)

765

In [53]:
# using the last {history_points} open high low close volume data points, predict the next open value
ohlcv_histories_normalised = np.array([data_normalised[i : i + history_points].copy() for i in range(len(data_normalised) - history_points)])
next_day_open_values_normalised = np.array([data_normalised[:,0][i + history_points].copy() for i in range(len(data_normalised) - history_points)])
next_day_open_values_normalised = np.expand_dims(next_day_open_values_normalised, -1)

next_day_open_values = np.array([data[:,0][i + history_points].copy() for i in range(len(data) - history_points)])
next_day_open_values = np.expand_dims(next_day_open_values_normalised, -1)

y_normaliser = preprocessing.MinMaxScaler()
y_normaliser.fit(np.expand_dims(next_day_open_values))

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [18]:
data_normalised[0:50]

array([[0.25782962, 0.25895824, 0.30637102, 0.28880232, 0.28880232,
        0.26725218],
       [0.26709272, 0.2710688 , 0.3159962 , 0.29966997, 0.29966997,
        0.28937488],
       [0.28117092, 0.2808462 , 0.32930041, 0.30655592, 0.30655592,
        0.30958616],
       [0.28905631, 0.29012555, 0.33482812, 0.31862683, 0.31862683,
        0.25039267],
       [0.29649549, 0.29344153, 0.34087445, 0.3214997 , 0.3214997 ,
        0.25117092],
       [0.30205854, 0.30040756, 0.34728295, 0.32375518, 0.32375518,
        0.27838129],
       [0.29838492, 0.29494225, 0.33991252, 0.32182732, 0.32182732,
        0.29423927],
       [0.30325254, 0.30592551, 0.35035598, 0.33400543, 0.33400543,
        0.3026245 ],
       [0.31454265, 0.31922208, 0.36088681, 0.34577395, 0.34577395,
        0.2939321 ],
       [0.33342297, 0.3321254 , 0.3602622 , 0.33958722, 0.33958722,
        0.39098753],
       [0.32425837, 0.33179773, 0.36634589, 0.35605573, 0.35605573,
        0.32027129],
       [0.33567965, 0

In [21]:
ohlcv_histories_normalised = np.array([data_normalised[i : i + history_points].copy() for i in range(len(data_normalised) - history_points)])

In [22]:
ohlcv_histories_normalised

array([[[0.25782962, 0.25895824, 0.30637102, 0.28880232, 0.28880232,
         0.26725218],
        [0.26709272, 0.2710688 , 0.3159962 , 0.29966997, 0.29966997,
         0.28937488],
        [0.28117092, 0.2808462 , 0.32930041, 0.30655592, 0.30655592,
         0.30958616],
        ...,
        [0.32789932, 0.32520513, 0.36689563, 0.34374534, 0.34374534,
         0.24373302],
        [0.32906049, 0.32842927, 0.35404111, 0.33258792, 0.33258792,
         0.25878565],
        [0.3170881 , 0.3121839 , 0.34510917, 0.32261483, 0.32261483,
         0.27036389]],

       [[0.26709272, 0.2710688 , 0.3159962 , 0.29966997, 0.29966997,
         0.28937488],
        [0.28117092, 0.2808462 , 0.32930041, 0.30655592, 0.30655592,
         0.30958616],
        [0.28905631, 0.29012555, 0.33482812, 0.31862683, 0.31862683,
         0.25039267],
        ...,
        [0.32906049, 0.32842927, 0.35404111, 0.33258792, 0.33258792,
         0.25878565],
        [0.3170881 , 0.3121839 , 0.34510917, 0.32261483, 0.322

In [26]:
next_day_open_values_normalised = np.array([data_normalised[:,0][i + history_points].copy() for i in range(len(data_normalised) - history_points)])

In [27]:
next_day_open_values_normalised

array([0.3041054 , 0.30167816, 0.2956492 , 0.27837626, 0.27833686,
       0.26283514, 0.23354368, 0.21559502, 0.24722836, 0.21031402,
       0.21235415, 0.22484483, 0.19776424, 0.19243086, 0.24053041,
       0.2329599 , 0.21417135, 0.22809867, 0.23169366, 0.23821463,
       0.25334894, 0.24888812, 0.26374038, 0.27513555, 0.26926403,
       0.26362234, 0.2523649 , 0.25590752, 0.22580916, 0.23678439,
       0.25241087, 0.25702929, 0.2310836 , 0.23848355, 0.22132208,
       0.21697257, 0.25560577, 0.24899302, 0.25414942, 0.27179634,
       0.28339476, 0.29374023, 0.2806986 , 0.27678217, 0.28143326,
       0.27988514, 0.29171963, 0.29365503, 0.27767427, 0.28880037,
       0.28398527, 0.27185544, 0.27009719, 0.28226642, 0.28077067,
       0.29583947, 0.30029388, 0.30343625, 0.31759981, 0.31169562,
       0.32110287, 0.32465861, 0.3261936 , 0.32309063, 0.31952848,
       0.31166279, 0.30262279, 0.31424747, 0.31395229, 0.30838268,
       0.29667263, 0.28301437, 0.28716688, 0.26764367, 0.28630

In [28]:
next_day_open_values_normalised = np.expand_dims(next_day_open_values_normalised, -1)

In [29]:
next_day_open_values_normalised

array([[0.3041054 ],
       [0.30167816],
       [0.2956492 ],
       [0.27837626],
       [0.27833686],
       [0.26283514],
       [0.23354368],
       [0.21559502],
       [0.24722836],
       [0.21031402],
       [0.21235415],
       [0.22484483],
       [0.19776424],
       [0.19243086],
       [0.24053041],
       [0.2329599 ],
       [0.21417135],
       [0.22809867],
       [0.23169366],
       [0.23821463],
       [0.25334894],
       [0.24888812],
       [0.26374038],
       [0.27513555],
       [0.26926403],
       [0.26362234],
       [0.2523649 ],
       [0.25590752],
       [0.22580916],
       [0.23678439],
       [0.25241087],
       [0.25702929],
       [0.2310836 ],
       [0.23848355],
       [0.22132208],
       [0.21697257],
       [0.25560577],
       [0.24899302],
       [0.25414942],
       [0.27179634],
       [0.28339476],
       [0.29374023],
       [0.2806986 ],
       [0.27678217],
       [0.28143326],
       [0.27988514],
       [0.29171963],
       [0.293

In [30]:
next_day_open_values = np.array([data.values[:,0][i + history_points].copy() for i in range(len(data) - history_points)])

In [31]:
next_day_open_values

array([2754.27001953, 2750.57006836, 2741.37988281, 2715.05004883,
       2714.98999023, 2691.36010742, 2646.70996094, 2619.35009766,
       2667.57006836, 2611.30004883, 2614.40991211, 2633.44995117,
       2592.16992188, 2584.04003906, 2657.36010742, 2645.82006836,
       2617.17993164, 2638.40991211, 2643.88989258, 2653.83007812,
       2676.89990234, 2670.10009766, 2692.73999023, 2710.11010742,
       2701.15991211, 2692.56005859, 2675.39990234, 2680.80004883,
       2634.91992188, 2651.64990234, 2675.4699707 , 2682.51000977,
       2642.95996094, 2654.23999023, 2628.08007812, 2621.44995117,
       2680.34008789, 2670.26000977, 2678.12011719, 2705.02001953,
       2722.69995117, 2738.4699707 , 2718.59008789, 2712.62011719,
       2719.70996094, 2717.35009766, 2735.38989258, 2738.34008789,
       2713.97998047, 2730.93994141, 2723.60009766, 2705.11010742,
       2702.42993164, 2720.97998047, 2718.69995117, 2741.66992188,
       2748.45996094, 2753.25      , 2774.84008789, 2765.84008

In [32]:
next_day_open_values = np.expand_dims(next_day_open_values_normalised, -1)

In [36]:
next_day_open_values

array([[[0.3041054 ]],

       [[0.30167816]],

       [[0.2956492 ]],

       [[0.27837626]],

       [[0.27833686]],

       [[0.26283514]],

       [[0.23354368]],

       [[0.21559502]],

       [[0.24722836]],

       [[0.21031402]],

       [[0.21235415]],

       [[0.22484483]],

       [[0.19776424]],

       [[0.19243086]],

       [[0.24053041]],

       [[0.2329599 ]],

       [[0.21417135]],

       [[0.22809867]],

       [[0.23169366]],

       [[0.23821463]],

       [[0.25334894]],

       [[0.24888812]],

       [[0.26374038]],

       [[0.27513555]],

       [[0.26926403]],

       [[0.26362234]],

       [[0.2523649 ]],

       [[0.25590752]],

       [[0.22580916]],

       [[0.23678439]],

       [[0.25241087]],

       [[0.25702929]],

       [[0.2310836 ]],

       [[0.23848355]],

       [[0.22132208]],

       [[0.21697257]],

       [[0.25560577]],

       [[0.24899302]],

       [[0.25414942]],

       [[0.27179634]],

       [[0.28339476]],

       [[0.29374

In [37]:
y_normaliser = preprocessing.MinMaxScaler()

In [48]:
y_normaliser.fit(np.expand_dims(next_day_open_values, axis=0))

ValueError: Found array with dim 4. MinMaxScaler expected <= 2.